config/routes.rb
Rails.application.routes.draw do
  get 'home/index' =>'home#index'

  get 'home/aboutus' =>'home#aboutus'

  get 'home/contactus' =>'home#contactus'
  get '/members' =>'home#members'
  get '/gallery' =>'home#gallery'
  get '/gallery1' =>'home#gallery1'
  get '/inaugration' => 'home#inaugration'
  get '/walkathon' =>'home#walkathon'
  get '/inaugration' => 'home#inaugration'

  #devise_for :admins
  devise_for :admins, :controllers => { :omniauth_callbacks => "admins/omniauth_callbacks" }

  resources :post_attachments
  root :to => redirect('/home/index')
  resources :posts
  get 'check' => 'posts#check'
  get '/movie/index'=>'movie#index'
  get '/trumpet/index' => 'trumpet#index'
 
  get '/women/index' =>'women#index'
 						
  get '/vogue/index' =>'vogue#index'
end

app/models/post_attachment.rb
class PostAttachment < ActiveRecord::Base
	 mount_uploader :avatar, AvatarUploader
     belongs_to :post
end

app/controllers/post_attachments_controller.rb
class PostAttachmentsController < ApplicationController
  before_action :set_post_attachment, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /post_attachments
  # GET /post_attachments.json
  def index
   if current_admin.has_role? "admin"
    @post_attachments = PostAttachment.all
   else 
    redirect_to trumpet_index_path
   end
  end

  # GET /post_attachments/1
  # GET /post_attachments/1.json
  def show
  end

  # GET /post_attachments/new
  def new
    if current_admin.has_role? "admin"
    @post_attachment = PostAttachment.new
    else
    redirect_to women_index_path
    end
  end

  # GET /post_attachments/1/edit
  def edit
#    authorize! :edit, @post_attachment
  end

  # POST /post_attachments
  # POST /post_attachments.json
  def create
    @post_attachment = PostAttachment.new(post_attachment_params)

    respond_to do |format|
      if @post_attachment.save
        format.html { redirect_to @post_attachment, notice: 'Post attachment was successfully created.' }
        format.json { render :show, status: :created, location: @post_attachment }
      else
        format.html { render :new }
        format.json { render json: @post_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_attachments/1
  # PATCH/PUT /post_attachments/1.json
  def update
    respond_to do |format|
      if @post_attachment.update(post_attachment_params)
        format.html { redirect_to @post_attachment, notice: 'Post attachment was successfully updated.' }
        format.json { render :show, status: :ok, location: @post_attachment }
      else
        format.html { render :edit }
        format.json { render json: @post_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post_attachments/1
  # DELETE /post_attachments/1.json
  def destroy
    @post_attachment.destroy
    respond_to do |format|
      format.html { redirect_to post_attachments_url, notice: 'Post attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_attachment
      @post_attachment = PostAttachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_attachment_params
      params.require(:post_attachment).permit(:post_id, :avatar)
    end
end

app/helpers/post_attachments_helper.rb
module PostAttachmentsHelper
end

app/views/post_attachments/_form.html.erb
<div class="row">
  <div class="small-2 large-6 columns">
<%= form_for(@post_attachment) do |f| %>
  <% if @post_attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post_attachment.errors.count, "error") %> prohibited this post_attachment from being saved:</h2>

      <ul>
      <% @post_attachment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.number_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.text_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit "Create",class: 'button' %>
  </div>
<% end %>
</div>
</div>

app/views/post_attachments/edit.html.erb
<div class="row">
  <div class="small-2 large-6 columns">
<h1>Editing post_attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @post_attachment %> |
<%= link_to 'Back', post_attachments_path %>
</div>
</div>

app/views/post_attachments/index.html.erb
<div class= "row">
<br>
<section class="small-8 small-centered columns">
<div class= "panel">
<span class="label"><h1>Listing post_attachments</h1></span>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Avatar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @post_attachments.each do |post_attachment| %>
      <tr>
        <td><%= post_attachment.post_id %></td>
        <td><%= post_attachment.avatar %></td>
                
          <td><div class="[tiny small large] button [alert round secondary]" ><%= link_to 'Show', post_attachment %></div></td>

          <td><div class="[tiny small large] button [alert round secondary]" ><%= link_to 'Edit', edit_post_attachment_path(post_attachment) %></div></td>

       
                <td><div class="[tiny small large] button [alert round secondary]" ><%= link_to 'Destroy', post_attachment, method: :delete, data: { confirm: 'Are you sure?' } %></div></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post attachment', new_post_attachment_path, :class => 'button' %>

</div>
</div>
</section>
</div>

app/views/post_attachments/new.html.erb
<div class="row">
  <div class="small-2 large-6 columns">
<h1>New post_attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', post_attachments_path %>
</div>
</div>

app/views/post_attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @post_attachment.post_id %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= @post_attachment.avatar %>
</p>
<%#if can? :update, @post_attachment%>
<%= link_to 'Edit', edit_post_attachment_path(@post_attachment) %> 
<%#end%>|
<%= link_to 'Back', post_attachments_path %>