config/routes.rb
Rails.application.routes.draw do
  get 'home/index' =>'home#index'

  get 'home/aboutus' =>'home#aboutus'

  get 'home/contactus' =>'home#contactus'
  get '/members' =>'home#members'
  get '/gallery' =>'home#gallery'
  get '/gallery1' =>'home#gallery1'
  get '/inaugration' => 'home#inaugration'
  get '/walkathon' =>'home#walkathon'
  get '/inaugration' => 'home#inaugration'

  #devise_for :admins
  devise_for :admins, :controllers => { :omniauth_callbacks => "admins/omniauth_callbacks" }

  resources :post_attachments
  root :to => redirect('/home/index')
  resources :posts
  get 'check' => 'posts#check'
  get '/movie/index'=>'movie#index'
  get '/trumpet/index' => 'trumpet#index'
 
  get '/women/index' =>'women#index'
 						
  get '/vogue/index' =>'vogue#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(admin)
    # Define abilities for the passed in user here. For example:
    #
    #   admin ||= Admin.new # guest user (not logged in)
    #   if admin.has_role? :admin
    #     can :manage, :all
    #   else
    #     can :read, :all
   #    end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base

  resourcify
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
  where(auth.slice(:provider, :uid)).first_or_create do |admin|
    admin.email = auth.info.email
    admin.password = Devise.friendly_token[0,20]
   #admin.username = auth.info.name   # assuming the user model has a name
    #user.image = auth.info.image # assuming the user model has an image
  end
end
end

app/models/post.rb
class Post < ActiveRecord::Base
  include Authority::UserAbilities 
  resourcify
   has_many :post_attachments
   belongs_to :admin, class_name: 'User'
   accepts_nested_attributes_for :post_attachments
end

app/models/post_attachment.rb
class PostAttachment < ActiveRecord::Base
	 mount_uploader :avatar, AvatarUploader
     belongs_to :post
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :admins, :join_table => :admins_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
#  before_action :authenticate_admin!
 def current_ability
  if request.fullpath =~ /\/locomotive/
    @current_ability ||= Locomotive::Ability.new(current_user)
  else
    @current_ability ||= Ability.new(current_user)
  end
end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
#  AdminNotify.notification(@admin).deliver
  def index
  end

  def aboutus
  end

  def contactus
  end

  def members
  end
  
  def gallery
  end
  def gallery1
  	
  end
end

app/controllers/movie_controller.rb
class MovieController < ApplicationController
	def index
		@posts=Post.where(:mr => true).order('id DESC')
		@postattach=PostAttachment.all
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  def index
    @posts = Post.all
    end
  def show
        @post_attachments = @post.post_attachments.all
  end

  # GET /posts/new
  def new
    @post = Post.new
    @post_attachment = @post.post_attachments.build
  end

  # GET /posts/1/edit
  def edit
  end 
 
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
     #    params[:post_attachments]['avatar'].each do |a|
      #    @post_attachment = @post.post_attachments.create!(:avatar => a, :post_id => @post.id)
      # end
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :mr, :vg, :tp, :wa,:couns)
    end
  # def check_permissions
   	
  # end
end

app/controllers/trumpet_controller.rb
class TrumpetController < ApplicationController
	def index
		@posts=Post.where(:tp => true).order('id DESC')
		@postattach=PostAttachment.all
	end
end

app/controllers/vogue_controller.rb
class VogueController < ApplicationController
	def index
		@posts=Post.where(:vg => true).order('id DESC')
		@postattach=PostAttachment.all
	end
end

app/controllers/women_controller.rb
class WomenController < ApplicationController
	def index
 		@posts=Post.where(:wa => true).order('id DESC')
		@postattach=PostAttachment.all
	end
	
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movie_helper.rb
module MovieHelper
end

app/helpers/post_attachments_helper.rb
module PostAttachmentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/trumpet_helper.rb
module TrumpetHelper
end

app/helpers/vogue_helper.rb
module VogueHelper
end

app/helpers/women_helper.rb
module WomenHelper
end

app/views/layouts/_bg.html.erb
<ul class="cb-slideshow">

     <li><span></span></li>
     <li><span></span></li>
     <li><span></span></li>
     <li><span></span></li>
     <li><span></span></li>
     <li><span></span></li>
</ul>

app/views/layouts/_footer.html.erb
<div class="container"> 
<footer id="footer-area">
        <!-- Footer Links Starts -->
            <div class="footer-links">
            <!-- Container Starts -->
                <div class="container">
                    <!-- Information Links Starts -->
                        <div class="col-md-2 col-sm-8">
                            <h4>Information</h4>
				<br>
			    <ul>
				    <li><a href="/home/index">Home</a></li> 
				    <li><a href="/home/aboutus">About Us</a></li>
	    			    <li><a href="/women/index">Women Achievers</a></li>
    				    <li><a href="/trumpet/index">Events</a></li> 

                            </ul>
                        </div>
                        <div class="col-md-2 col-sm-8">
                            <h4>Service</h4>
				<br>
			    <ul>
                    <li><a href="" data-reveal-id="myModal">Contact Us</a>

                    <div id="myModal" class="reveal-modal" data-reveal>
                    <%= render '/home/contactus'%>
                    <a onclick="history.go(-0);return true;" class="close-reveal-modal">&#215;</a>
                    </div></li>
				    <li><a href="/members">Members</a></li>
			    </ul>
		    </div>
    			    <div class="col-md-2 col-sm-6">
                            <h4>Follow Us</h4>
				<br>
			    <ul>
				    <li><a target="_blank" href="https://www.facebook.com/AakritiCEG?fref=ts"><span class="avatar"><i class="fa fa-facebook">&nbsp;</i></span>Facebook</a></li>
    				    <li><a target="_blank" href="#"><span class="avatar"><i class="fa fa-twitter">&nbsp;</i></span>Twitter</a></li>
                           </ul>
		   </div>
	   </div>
   </div>
		   </footer>
</div>


<body>

app/views/layouts/_login_links.html.erb
        
    <% if  admin_signed_in? %>
<li><a href="/admins/edit"><i class="fa fa-gear"></i><span class="hidden-sm hidden-xs"> Settings</span></a></li>
<li class="divider"></li>
<li><%=link_to '<i class="fa fa-power-off"><span class="hidden-sm hidden-xs">Log Out</span></i>'.html_safe, destroy_admin_session_path, method: :delete %></li>     <% else %>
    <li>
    <a href="/admins/sign_up"><i class="fa fa-unlock" title="" data-original-title="Register"></i>
     <span class="hidden-sm hidden-xs"> Register</span> </a>
<li class="divider"></li>
 <li><a href="/admins/sign_in">
<i class="fa fa-lock" title="" data-original-title="Login"></i>
<span class="hidden-sm hidden-xs">
Login</span>
</a>
</li>
 	  <li class="divider"></li>
	<% end %>
        </ul>

app/views/layouts/_message.html.erb
<div class = "row">
<% if notice %>
  <p data-alert class="alert-box success radius" >
    <a class="close">&times;</a>
  <%= notice %></p>
<% end %>


<% if alert %>
  <p data-alert class="alert-box alert round">
  <a class="close">&times;</a>
  <%= alert %></p>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>
    <%= content_for?(:title) ? yield(:title) : " Aakriti" %></title>

    <%= stylesheet_link_tag    "application"  %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
    <link rel="shortcut icon" href="/images/fav1.ico">
    <!--Background-->
    <link rel="stylesheet" type="text/css" href="/css/demo.2.css">
    <link rel="stylesheet" type="text/css" href="/css/style2.css" > 
    <!--   <script type="text/javascript" src="/js/modernizr.custom.86080.js"></script> -->
    <!--Prettyphoto-->
    <link href="/assets/bootstrap.min.css" rel="stylesheet">
    <link href="/assets/font-awesome.min.css" rel="stylesheet">
    <link href="/assets/prettyPhoto.css" rel="stylesheet">
    <link href="/assets/main.css" rel="stylesheet">
    <!-- Fonts -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">	 
    <!--Circular-->
     <link rel="stylesheet" type="text/css" href="/css/vogue/demo.css" >
     <link rel="stylesheet" type="text/css" href="/css/vogue/style.css" >
     <link rel="stylesheet" type="text/css" href="/css/vogue/jquery.jscrollpane.css" media="all" >
	 
    </head>

  <body>
   <%= render '/layouts/bg'%>
   <%= yield %>
    
   <%= javascript_include_tag "application" %>
  </body>
</html>